@startuml
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|.. AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList   {
- elementData:int
- size():void
}
enum TimeUnit {
DAYS
HOURS
MINUTES
}








@enduml