@startuml
    interface Implementor {
       + opertionImpl():Object
    }
    class AImplemetor{
       + opertionImpl():object
    }

    class BImplemetor{
       + opertionImpl():object
    }

    abstract class Abstraction{
        - implementor:Implementor
        # Abstraction(Implementor imple)
        + opertion():void
    }

    class RefinedAbstraction{
       - implementor:Implementor
       # RefinedAbstraction(Implementor imple)
       + opertion():void
    }


       Client.>Abstraction
       Abstraction o- Implementor
       Abstraction <|-- RefinedAbstraction
       Implementor<|..AImplemetor
       Implementor<|..BImplemetor


@enduml