@startuml
  class SingleDemo{
     - instance:SingleDemo
     - SingleDemo()
     + getInstance():SingleDemo
  }

  class Client{
     + instance:SingleDemo
  }

  Client..>SingleDemo
  SingleDemo --o SingleDemo

@enduml