@startuml
    interface Target{
      + request():void
    }

    class Adaptee{
      + specifiRequest():void
    }

    class Adapter{
      + request():void
    }

    Adaptee<|--Adapter
    Target<|--Adapter
    Client.>Target

@enduml