@startuml
         interface Target{
          + request():void
        }

        class Adaptee{
          + specifiRequest():void
        }

        class Adapter{
          - adaptee: Adaptee
          + request():void
        }

         Client .> Target
         Target<|..Adapter
         Adapter -o Adaptee

@enduml