@startuml

    interface IFunction{
       + getResult(): String
    }
    class FunctionImpl{
       - functionName:String
       + getResult(): String
    }
    class FunctionProxy{
      - function : FunctionImpl
       + getResult(): String
    }

    Client.>IFunction
    IFunction<|..FunctionImpl
    IFunction<|..FunctionProxy
    FunctionProxy o-FunctionImpl
    Client ..>FunctionProxy

@enduml